version: '3'

services:
  test-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: algomart-api-test
    ports:
      - "6543:5432"
